/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Dao_CadastroProduto;
import Dao.conexao;
import Model.CadastroPeça;
import Utilitarios.ModeloTabela;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.io.Serializable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Gabriel
 */
public class TelaPeças extends javax.swing.JInternalFrame {
   
    conexao con = new conexao();
    conexao con_pequisa = new conexao();
    Dao_CadastroProduto Dao_cadprod = new Dao_CadastroProduto();
    CadastroPeça cp= new CadastroPeça() ;
    public TelaPeças() {
        
       
        initComponents();
        
        centralizarComponente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastropane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxDescreveProduto1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxNomeforne1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        BtPesquisarProduto = new javax.swing.JButton();
        BtLimparC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxCodProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxDescreveProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxQtdProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxPrecoProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxPrecoProdVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtNovo = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        TxNomeforne = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Produto");

        jLabel8.setText("Descriçao do Produto");

        jLabel12.setText("Nome Fornecedor");

        TxNomeforne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNomeforne1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela);

        BtPesquisarProduto.setText("Pesquisar");
        BtPesquisarProduto.setEnabled(false);
        BtPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarProdutoActionPerformed(evt);
            }
        });

        BtLimparC.setText("Limpar");
        BtLimparC.setEnabled(false);
        BtLimparC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxNomeforne1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                    .addComponent(TxDescreveProduto1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtLimparC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxDescreveProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxNomeforne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtLimparC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cadastropane.addTab("Consulta", jPanel2);

        jLabel1.setText("Cod Produto");

        TxCodProduto.setEditable(false);

        jLabel2.setText("Descriçao do Produto");

        TxDescreveProduto.setEditable(false);

        jLabel3.setText("Quantidade");

        TxQtdProd.setEditable(false);

        jLabel4.setText("Preço Pago");

        TxPrecoProd.setEditable(false);

        jLabel5.setText("Preço Venda Unitario");

        TxPrecoProdVenda.setEditable(false);

        jLabel6.setText("Nome Fornecedor");

        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtSalvar.setText("Salvar");
        BtSalvar.setEnabled(false);
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar");
        BtAlterar.setEnabled(false);

        BtExcluir.setText("Excluir");
        BtExcluir.setEnabled(false);

        TxNomeforne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        TxNomeforne.setEnabled(false);

        jButton1.setText("Cancelar");
        jButton1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxQtdProd)
                            .addComponent(TxCodProduto))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(TxPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxPrecoProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(BtAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtExcluir)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxNomeforne, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))))
                            .addComponent(TxDescreveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtSalvar)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxDescreveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxPrecoProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxNomeforne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovo)
                    .addComponent(BtSalvar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir)
                    .addComponent(jButton1))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        Cadastropane.addTab("Cadastro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cadastropane, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cadastropane, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        Cadastropane.getAccessibleContext().setAccessibleName("Cadastro");

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try {
            if (TxCodProduto.getText().length() != 0 || TxDescreveProduto.getText().length() != 0 || TxNomeforne.getSelectedItem().equals("Selecione") || TxPrecoProd.getText().length() != 0 || TxPrecoProdVenda.getText().length() != 0 || TxQtdProd.getText().length() != 0) {
                JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
            } else {
            
              
              cp= new CadastroPeça();
         
              cp.setCodproduto(Integer.valueOf(TxCodProduto.getText()));
              cp.setDescriprod(TxDescreveProduto.getText());
              cp.setNomeforne(String.valueOf(TxNomeforne.getSelectedItem()));
              cp.setQtdprod(Integer.valueOf(TxQtdProd.getText()));
              cp.setPrecopag(Float.valueOf(TxPrecoProd.getText()));
              cp.setPrecovenda(Float.valueOf(TxPrecoProdVenda.getText()));
             
              
                Dao_cadprod.salvar(cp);

                JOptionPane.showMessageDialog(null, "Cadastro de produto realizado com susseso!");
                TxCodProduto.setText("");
                TxDescreveProduto.setText("");
                TxNomeforne.setSelectedItem("Selecione");
                TxPrecoProd.setText("");
                TxPrecoProdVenda.setText("");
                TxQtdProd.setText("");
                TxCodProduto.setEnabled(false);
                TxDescreveProduto.setEnabled(false);
                TxNomeforne.setEnabled(false);
                TxPrecoProd.setEnabled(false);
                TxPrecoProdVenda.setEnabled(false);
                TxQtdProd.setEditable(false);
                TxDescreveProduto.setEditable(false);
                TxNomeforne.setEditable(false);
                TxPrecoProd.setEditable(false);
                TxPrecoProdVenda.setEditable(false);
                TxQtdProd.setEditable(false);
                TxCodProduto.setEditable(false);

            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
            preencherCombo();
            BtSalvar.setEnabled(true);
            BtNovo.setEnabled(false);
            TxDescreveProduto.setText("");
            TxNomeforne.setSelectedItem("Selecione");
            TxPrecoProd.setText("");
            TxPrecoProdVenda.setText("");
            TxQtdProd.setText("");
            TxCodProduto.setEnabled(true);
            TxDescreveProduto.setEnabled(true);
            TxNomeforne.setEnabled(true);
            TxPrecoProd.setEnabled(true);
            TxNomeforne.setEnabled(true);
            TxPrecoProdVenda.setEnabled(true);
            TxQtdProd.setEditable(true);
            TxDescreveProduto.setEditable(true);
            TxPrecoProd.setEditable(true);
            TxPrecoProdVenda.setEditable(true);
            TxQtdProd.setEditable(true);
            
    }//GEN-LAST:event_BtNovoActionPerformed

    private void TxNomeforne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNomeforne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNomeforne1ActionPerformed

    private void BtLimparCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtLimparCActionPerformed

    private void BtPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarProdutoActionPerformed
        cp.setPesquisa(TxDescreveProduto1.getText());
       // cp = Dao_cadprod.buscaProduto(cp);
        //TxCodProduto.setText(String.valueOf(cp.getCodproduto()));
        //TxDescreveProduto.setText(cp.getDescriprod());
       // TxNomeforne.setSelectedItem(cp.getNomeforne());
        //TxQtdProd.setText(String.valueOf(cp.getQtdprod()));
        //TxPrecoProd.setText(String.valueOf(cp.getPrecopag()));
        //TxPrecoProdVenda.setText(String.valueOf(cp.getPrecovenda()));
            TxCodProduto.setEnabled(false);
            TxDescreveProduto.setEnabled(false);
            TxNomeforne.setEnabled(false);
            TxPrecoProd.setEnabled(false);
            TxNomeforne.setEnabled(false);
            TxPrecoProdVenda.setEnabled(false);
            TxQtdProd.setEditable(false);
            TxDescreveProduto.setEditable(false);
            TxPrecoProd.setEditable(false);
            TxPrecoProdVenda.setEditable(false);
            TxQtdProd.setEditable(false);
            TxCodProduto.setEditable(false);
        
        preencherTabela("select *from produto where nome_produto like '% "+cp.getPesquisa()+"%'");
        
        
        
    }//GEN-LAST:event_BtPesquisarProdutoActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        String nome_produto = "" + tabela.getValueAt(tabela.getSelectedRow(), 0);
        con.conexao();
        
        con_pequisa.conexao();
        con.executeSQL("select *from produto where nome_produto='" + nome_produto + "'");
       
        try {
            con.resultset.first();
            TxCodProduto.setText(String.valueOf(con.resultset.getInt("id_produto")));
            TxDescreveProduto.setText(con.resultset.getString("nome_produto"));
            con_pequisa.executeSQL("select *from fornecedores where id_fornecedor=" + con.resultset.getInt("id_fornecedor"));
            con_pequisa.resultset.first();
            TxNomeforne.setSelectedItem(con_pequisa.resultset.getString("nome_fornecedor"));
            con_pequisa.closeInstance();
            TxQtdProd.setText(String.valueOf(con.resultset.getInt("quantidade")));
            TxPrecoProd.setText(String.valueOf(con.resultset.getFloat("preco_compra")));
            TxPrecoProdVenda.setText(String.valueOf(con.resultset.getFloat("preco_venda")));
            con.closeInstance();
            TxCodProduto.setEnabled(true);
            TxDescreveProduto.setEnabled(true);
            TxNomeforne.setEnabled(true);
            TxPrecoProd.setEnabled(true);
            TxNomeforne.setEnabled(true);
            TxPrecoProdVenda.setEnabled(true);
            TxQtdProd.setEditable(true);
            TxDescreveProduto.setEditable(true);
            TxPrecoProd.setEditable(true);
            TxPrecoProdVenda.setEditable(true);
            TxQtdProd.setEditable(true);
            TxCodProduto.setEditable(true);
        } catch (SQLException s) {

        }


    }//GEN-LAST:event_tabelaMouseClicked
     public void preencherCombo() {
         con.conexao();
         con.executeSQL("select *from fornecedores order by nome_fornecedor");
         try{
             con.resultset.first();
             do{
              TxNomeforne.addItem(con.resultset.getString("nome_fornecedor"));
             }while(con.resultset.next());
             con.closeInstance();
         }
         catch(SQLException ex){
         
           JOptionPane.showMessageDialog(null,"Erro ao preencher combobox"+ex);
         
         }
       
         
     }
   
    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Nome Produto","Quantidade","Preço","Nome do Fornecedor"};
        con.conexao();
        con.executeSQL(sql);
        try {
            con.resultset.first();
            do {
                dados.add(new Object[]{con.resultset.getString("nome_produto"),con.resultset.getString("quantidade"),con.resultset.getString("preco_venda"),con.resultset.getString("nome_fornecedor")});
            } while (con.resultset.next());
           con.closeInstance();
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao prencher o Array List" + ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(110);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(115);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtLimparC;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtPesquisarProduto;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTabbedPane Cadastropane;
    private javax.swing.JTextField TxCodProduto;
    private javax.swing.JTextField TxDescreveProduto;
    private javax.swing.JTextField TxDescreveProduto1;
    private javax.swing.JComboBox<String> TxNomeforne;
    private javax.swing.JTextField TxNomeforne1;
    private javax.swing.JTextField TxPrecoProd;
    private javax.swing.JTextField TxPrecoProdVenda;
    private javax.swing.JTextField TxQtdProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
